// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members

/// Firebase configuration placeholders.
///
/// Replace every value with the actual configuration generated by the
/// Firebase CLI (`flutterfire configure`) before releasing your app.
library;

import 'package:firebase_core/firebase_core.dart';
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        return linux;
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not configured for this platform.',
        );
    }
  }

  /// Android config generated from `google-services.json`.
  static final FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCjpvuWvcRucagAzKFwqelTQbHJ6Ema9oU',
    appId: '1:605821517608:android:1117803c4c77a7632c9a1d',
    messagingSenderId: '605821517608',
    projectId: 'langxc-46763',
    storageBucket: 'langxc-46763.firebasestorage.app',
  );

  /// 🔧 TODO: Replace with the values from your iOS `GoogleService-Info.plist`.
  static final FirebaseOptions ios = FirebaseOptions(
    apiKey: 'PASTE_IOS_API_KEY',
    appId: 'PASTE_IOS_APP_ID',
    messagingSenderId: 'PASTE_IOS_MESSAGING_SENDER_ID',
    projectId: 'langxc-46763',
    storageBucket: 'langxc-46763.firebasestorage.app',
    iosBundleId: 'com.example.langxc',
  );

  /// 🔧 TODO: Replace with macOS `GoogleService-Info.plist` values.
  static final FirebaseOptions macos = FirebaseOptions(
    apiKey: 'PASTE_MACOS_API_KEY',
    appId: 'PASTE_MACOS_APP_ID',
    messagingSenderId: 'PASTE_MACOS_MESSAGING_SENDER_ID',
    projectId: 'langxc-46763',
    storageBucket: 'langxc-46763.firebasestorage.app',
    iosBundleId: 'com.example.langxc.macos',
  );

  /// 🔧 TODO: Register web app in Firebase Console to get appId & measurementId.
  /// See FIREBASE_WEB_SETUP.md for complete instructions.
  static final FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCjpvuWvcRucagAzKFwqelTQbHJ6Ema9oU',
    appId:
        '1:605821517608:web:0d7d9a0ff0ec22532c9a1d', // ← Get from Firebase Console
    messagingSenderId: '605821517608',
    projectId: 'langxc-46763',
    authDomain: 'langxc-46763.firebaseapp.com',
    storageBucket: 'langxc-46763.firebasestorage.app',
    measurementId: 'G-BNH3J8MN6K', // ← Get from Firebase Console
  );

  /// 🔧 TODO: Replace with the Windows values from `flutterfire configure`.
  static final FirebaseOptions windows = FirebaseOptions(
    apiKey: 'PASTE_WINDOWS_API_KEY',
    appId: 'PASTE_WINDOWS_APP_ID',
    messagingSenderId: 'PASTE_WINDOWS_MESSAGING_SENDER_ID',
    projectId: 'langxc-46763',
    storageBucket: 'langxc-46763.firebasestorage.app',
  );

  /// 🔧 TODO: Replace with the Linux values from `flutterfire configure`.
  static final FirebaseOptions linux = FirebaseOptions(
    apiKey: 'PASTE_LINUX_API_KEY',
    appId: 'PASTE_LINUX_APP_ID',
    messagingSenderId: 'PASTE_LINUX_MESSAGING_SENDER_ID',
    projectId: 'langxc-46763',
    storageBucket: 'langxc-46763.firebasestorage.app',
  );
}
